In [19]:
import cv2


# 加载图像


In [20]:
img = cv2.imread("parrot.png", cv2.IMREAD_COLOR) # 读取图片
# 输出图片类型
print(type(img))
# 输出图像数组
print(img)
# 输出图像形状
print(img.shape)
print(img.dtype)
print(img.size)

<class 'numpy.ndarray'>
[[[ 96 142 150]
  [ 87 134 142]
  [ 81 134 144]
  ...
  [ 91 113 118]
  [ 97 116 121]
  [ 86 103 106]]

 [[ 92 141 149]
  [ 85 136 146]
  [ 81 136 145]
  ...
  [ 92 114 120]
  [ 99 118 123]
  [ 88 105 108]]

 [[ 90 145 154]
  [ 83 140 149]
  [ 79 140 150]
  ...
  [ 90 114 120]
  [ 97 117 122]
  [ 85 104 107]]

 ...

 [[ 65 106 121]
  [ 63 106 121]
  [ 62 106 123]
  ...
  [ 34  75  97]
  [ 39  72  91]
  [ 32  65  81]]

 [[ 67 106 121]
  [ 65 106 121]
  [ 63 106 123]
  ...
  [ 34  75  97]
  [ 37  70  89]
  [ 32  65  80]]

 [[ 68 104 120]
  [ 66 105 120]
  [ 61 105 122]
  ...
  [ 35  75  94]
  [ 39  72  88]
  [ 36  68  81]]]
(357, 544, 3)
uint8
582624


In [21]:
# 读取图像，缩小为原来的1/2
img = cv2.imread('parrot.png', cv2.IMREAD_REDUCED_COLOR_2)
cv2.imshow('parrot', img)
key = cv2.waitKey(0)

if (key == ord('q')):
    exit()